### ISSUE TITLE
Suggestion: Reset variables on map start

### ISSUE THREAD

**Issue by Lach993** [RoanH/KeysPerSecond#22] opened 2020-01-31 05:25 UTC
like the title says we should be able to define variables that reset on map restart. i.e. lets say i want my mania keys, average and maximun to restart every time i start a map. i put that in a config file and use it that way. i would like to use this while streaming but im the kind of person to restart them map 10 times during the intro. whcih it would be obnoxious to restart the settings every time.

**Comment by RoanH** [comment] 2020-02-03 13:53
This is an interesting idea. Although I'm currently not exactly certain how doable it'll be to implement. I know I can listen for the MSN event osu! sends out to detect when the song changes, but I don't know if osu! resends this event when a map is restarted so I'll have to test that.

Alternatively shouldn't it work to just rebind the reset stats shortcut key to be the same as the osu! restart map key?

**Comment by Lach993** [comment] 2020-02-05 12:34
i tried doing that remapping things, but i noticed sometimes that it would bring the monitor into the foreground, causing osu to pick up your inputs slowly as it lowers the refreshing of cursor and everything else when it is in background, and sometimes restart the map constantly because it hasn't received the "restart key release" (because the monitor is brought into foreground), it just does some wacky things, and playing mania never actually clicking my mouse i need to go to it and click before being able to play (i havent used it for a while except in background cause i wanted to see how many times i click in a day)

**Comment by Lach993** [comment] 2020-02-05 12:38
on that note, it clicked it that this might be the issue the other person was experiencing with the following:
> Hi, This is great work!
> 
> I used KeysPerSecond-v8.2.exe in win10.
> I found that OSU! sometimes can't read keys when I play OSU!mania and used KeysPerSecond and OBS.
> This caused that keys I pressed to be judged as a miss.
> This interval will occur once every 5-30 seconds.
> But I don't understand why was bug happen, maybe it just a case.
> 
> Thank you

as it is trying to bring it into foreground.

**Comment by RoanH** [comment] 2020-02-07 22:17
That's certainly an interesting theory. I don't think that there is any code currently that ever brings the window into the foreground. And rendering on top of osu! when it is running in full screen mode is impossible so that would drop osu! out of full screen mode and could certainly cause the reported symptoms. I wasn't able to reproduce it but I suspect that to be because it either only happens on certain keyboard layouts, doesn't always happen or because it's an edge case in the library handling the native key events. I'll try to do some more testing to see if I can find a reliable way to reproduce it, at least now I have a somewhat more specific target to look at. Thank for your help so far!

**Comment by Lach993** [comment] 2020-02-09 06:20
ill do some more testing when i have time, ill check it with OBS running and have all apps running in different modes. (note i might not have time for like 5 days, but i will get to it eventually :D)

**Comment by RoanH** [comment] 2020-02-09 11:35
Thanks, much appreciated :D

**Comment by RoanH** [comment] 2022-01-03 03:40
I'm going to close this since I have since updated the native key handling issue (and another update will come in v8.5). This might have resolved the issue with the key binds (but I can't test that). I've also decided to not support the osu! MSN event, mostly because this is an ancient system that will most likely never be supported in the osu!lazer so I wouldn't be able to support it.

**Closed by RoanH** 2022-01-03 03:40 UTC
Labels: enhancement
