### ISSUE TITLE
Reset totals command defaulting back to ctrl + I

### ISSUE THREAD

**Issue by examplejoshuadeath** [RoanH/KeysPerSecond#40] opened 2021-09-21 09:59 UTC
If I change the command for Reset totals from Ctrl + I to another shortcut, it works as intended for the current session. However, if the config is saved and loaded again, it defaults back to Ctrl + I in the commands configuration panel, as well as in practice. However, looking at the file in Notepad+ +, I can see that whatever command I set has been saved.  

This is on version 8.4. I have not attempted reinstalling because setting it up for each session is less of an issue than reconfiguring settings for me.

**Comment by RoanH** [comment] 2021-09-21 10:50
Thank you for the report, I can reproduce this without any issues and also found the cause after a short investigation. Turns out that I'm reading the setting as `keyResetTotal` instead of `keyResetTotals` by accident... I'll fix this in v8.5, but in the meantime you can 'fix' this by editing your config and renaming `keyResetTotals` to `keyResetTotal` (though note that you'll have to undo this again when you update to v8.5)

**Comment by RoanH** [comment] 2021-10-09 01:41
This should be fixed in the upcoming next release now (v8.5).

**Closed by RoanH** 2021-10-09 01:41 UTC
Labels: bug
