### ISSUE TITLE
Issue pressing all keys at the same time

### ISSUE THREAD

**Issue by OhNoItzBuster** [RoanH/KeysPerSecond#69] opened 2022-12-31 21:27 UTC
if i press all keys at once, sometimes one key doesn't light up and sometimes if i'm playing it randomly decides to keep lighting up a key that isn't pressed until i press it again. fix please.

**Comment by RoanH** [comment] 2023-03-12 14:19
This sounds like a normal limitation of most keyboards called ghosting (see [this explanation from Microsoft](https://www.microsoft.com/applied-sciences/projects/anti-ghosting-demo) for example). There are also a number of related issues as detailed by Wikipedia: https://en.wikipedia.org/wiki/Key_rollover

Pressing all keys on the keyboard isn't really something that many keyboard properly support, so I'm expecting that you are running into this limitation (you can checking using the tool on that article from Microsoft if you want). However, if there is a discrepancy between what Microsoft's tool can detect and what KeysPerSecond shows, then please let me know.

**Comment by RoanH** [comment] 2023-03-27 15:15
Going to close this for now, feel free to reopen if the issue is different from what I explained.

**Closed by RoanH** 2023-03-27 15:15 UTC
Labels: question
